<a href="https://colab.research.google.com/github/polly-oh/parrot/blob/main/0316%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [137]:
import numpy as np

In [138]:
 #1. data type이 정수형인 3 by 3 단위행렬 A를 만드시오

In [139]:
A= np.eye(3, dtype='int')
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [140]:
#2. A의 원소 중 1을 모두 10으로 바꾸어서 A를 출력하시오

In [141]:
A[A==1]=10
A

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])

In [142]:
#3. 1부터 20까지(정수) 범위 내에서 짝수만을 나열한 ndarray B를 만드시오

In [143]:
B=np.arange(2,21,2, dtype='int')
B

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [144]:
#4. ndarray B를 2 by 5 행렬로 바꾸고 마지막 열의 원소에만 나누기 2를 연산하여 다시 B를 출력하시오

In [145]:
B= B.reshape(2,5)
B[1:]=B[1:]/2
B

array([[ 2,  4,  6,  8, 10],
       [ 6,  7,  8,  9, 10]])

In [146]:
#5. 다음 결과를 출력하도록 코드를 작성하시오

In [147]:
#(array([1., 4., 7.]), 3.0)

In [148]:
 np.linspace(1, 7., num=3, retstep=True) 

(array([1., 4., 7.]), 3.0)

In [149]:
#6. 0부터 9까지의 정수를 랜덤으로 나열한 ndarray C를 출력하시오

In [150]:
C=np.random.randint(0,10,7)
C

array([5, 6, 9, 8, 9, 2, 4])

In [151]:
#7. 1부터 45까지의 정수 중 6개를 random sampling하여 ndarray로 출력하시오

In [152]:
np.random.randint(1,46,6)

array([40, 45,  8, 30, 41, 12])

In [153]:
#8-1. 표준정규분포 하에서 3 by 3 난수를 발생시켜 ndarray a로 저장
#8-2. 각 열의 최댓값 행vector를 변수 b에, 각 열의 최솟값 행vector 변수 c에 저장
#8-3. b와 c의 차원을 알맞게 변환시켜, ndarray a에 b와 c를 추가시킨 ndarray aa를 출력하시오

In [154]:
a=np.random.randn(3,3)
b=a.max(0)
c=a.min(0)
aa=np.append(np.append(a,b),c).reshape(5,3)
aa

array([[-0.45213872, -1.25384108, -0.0989065 ],
       [ 1.30048582,  1.14130288,  0.90868711],
       [-0.55255217,  0.47658155,  1.14752717],
       [ 1.30048582,  1.14130288,  1.14752717],
       [-0.55255217, -1.25384108, -0.0989065 ]])

In [155]:
#8-4. andarry aa를 행별 내림차순하여 나타내시오

In [156]:
aa=np.sort(aa)
aa[:,::-1]

array([[-0.0989065 , -0.45213872, -1.25384108],
       [ 1.30048582,  1.14130288,  0.90868711],
       [ 1.14752717,  0.47658155, -0.55255217],
       [ 1.30048582,  1.14752717,  1.14130288],
       [-0.0989065 , -0.55255217, -1.25384108]])

In [157]:
#8-5. ndarray aa를 파일명 'aa.txt', 소수점 이하 6자리까지, 구분자를 tap 문자로 하여 파일로 저장
#8-6. 'aa.txt'를 출력하시오

In [158]:
np.savetxt('aa.txt', aa, fmt = '%.6f', delimiter='\t')
np.loadtxt('aa.txt', dtype='float', delimiter = '\t')

array([[-1.253841, -0.452139, -0.098907],
       [ 0.908687,  1.141303,  1.300486],
       [-0.552552,  0.476582,  1.147527],
       [ 1.141303,  1.147527,  1.300486],
       [-1.253841, -0.552552, -0.098907]])

In [159]:
#9-1. 1부터 9까지의 정수를 차례로 나열한 3 by 3 행렬 X를 만드시오
#9-2. 열 index만큼 각 열을 반복하여 3 by 6 행렬로 변형하시오 (첫 번째 열 한 번 반복, ...)
#9-3. 각 행별 mean값을 구한 행vector를 변수 y, 각 행별 std값을 구한 행vector를 변수 z에 저장하시오

In [160]:
X=np.arange(1,10).reshape(3,3)
X=X.repeat([1,2,3],axis=1)
y=X.mean(1)
z=X.std(1)

In [161]:
#9-4. y의 원소값이 첫번째 열, z의 원소값이 두 번째 열이 되도록 3 by 2 행렬 Y로 저장하고 출력하시오

In [162]:
Y=np.append(y,z).reshape(2,3).T
Y

array([[2.33333333, 0.74535599],
       [5.33333333, 0.74535599],
       [8.33333333, 0.74535599]])

In [163]:
#9-5. tile 함수를 활용해보세요 (ndarray Y 사용, shape은 각자 재량)

In [164]:
#np.tile(Y,2)
#np.tile(Y,4)
#np.tile(Y,(1,2))
#np.tile(Y,(2,1))
np.tile(Y, (2,2,2))

array([[[2.33333333, 0.74535599, 2.33333333, 0.74535599],
        [5.33333333, 0.74535599, 5.33333333, 0.74535599],
        [8.33333333, 0.74535599, 8.33333333, 0.74535599],
        [2.33333333, 0.74535599, 2.33333333, 0.74535599],
        [5.33333333, 0.74535599, 5.33333333, 0.74535599],
        [8.33333333, 0.74535599, 8.33333333, 0.74535599]],

       [[2.33333333, 0.74535599, 2.33333333, 0.74535599],
        [5.33333333, 0.74535599, 5.33333333, 0.74535599],
        [8.33333333, 0.74535599, 8.33333333, 0.74535599],
        [2.33333333, 0.74535599, 2.33333333, 0.74535599],
        [5.33333333, 0.74535599, 5.33333333, 0.74535599],
        [8.33333333, 0.74535599, 8.33333333, 0.74535599]]])

In [165]:
# 수고 많으셨습니다!!